version: '3.7'

services:
  server:
    container_name: server
    build:
      context: ./server
      target: development
    volumes:
      - ./server:/usr/src/app
    ports:
      - 8000:${PORT}
    command: ${CONTAINER_CMD:-npm run start:dev}
    tty: true
    env_file:
      - .env

networks:
  default:
    external: true
    name: cassandra