version: '3.7'

services:
  cass1:
    image: cassandra:3.11.8
    container_name: cass1
    deploy:
      resources:
        limits:
          memory: 1g
    ports:
      - 9042:9042
    volumes:
      - ./.db/data/cass1:/var/lib/cassandra
      - ./.db/etc/cass1:/etc/cassandra
    env_file:
      - .env

  cass2:
    image: cassandra:3.11.8
    container_name: cass2
    deploy:
      resources:
        limits:
          memory: 1g
    ports:
      - 9043:9042
    volumes:
      - ./.db/data/cass2:/var/lib/cassandra
      - ./.db/etc/cass2:/etc/cassandra
    env_file:
      - .env
    depends_on:
      - "cass1"

  cass3:
    image: cassandra:3.11.8
    container_name: cass3
    deploy:
      resources:
        limits:
          memory: 1g
    ports:
      - 9044:9042
    volumes:
      - ./.db/data/cass3:/var/lib/cassandra
      - ./.db/etc/cass3:/etc/cassandra
    env_file:
      - .env
    depends_on:
      - "cass2"

networks:
  default:
    external: true
    name: cassandra